version: '3.8'

services:
  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017" # Expose MongoDB port to host
    volumes:
      - mongo-data:/data/db # Persist MongoDB data

  app:
    build: .
    container_name: user-app
    restart: always
    ports:
      - "5000:5000" # Expose app port to host
    environment:
      - DB_URI=mongodb://mongo:27017/user_management
      - JWT_SECRET=your_jwt_secret
      - PORT=5000
    depends_on:
      - mongo

volumes:
  mongo-data:
